### ISSUE TITLE
About paper_id

### ISSUE THREAD

**Issue by rigggby** [ChenxinAn-fdu/CGSum#2]
Hi, thank you for sharing your awesome work, is the paper_id in your dataset created by yourself or is there any way I can link them to other resources such as arxiv or semantic scholar, thanks.

**Comment by ChenxinAn-fdu** [comment]
Thank you for your interests in our work,  we keep the paper_id in the origin S2ORC corpus(https://github.com/allenai/s2orc). Allenai has provided metadata files of these  papers  where you can retrieve the metadata by the paper_id.  You can download them from https://github.com/allenai/s2orc.

**Comment by rigggby** [comment]
Thank you for your answer, I will check that one out.
